redis:
  image: redis
  container_name: cache
  expose:
    - 6379


app:
  build: ./
  volumes:
    - ./:/var/www/app
  links:
    - redis 
  ports:
    - 3000:3000
  environment:
    - NODE_ENV=development
    - REDIS_URL=redis://cache 
    - PORT=3000
  command:
    sh -c 'npm i && npm start'